package be.driesstelten.FarmingUtilities.data;

import cpw.mods.fml.common.ModMetadata;

public class ModData {
	
	public static final String ID = "farmingutilities";
	public static final String NAME = "Farming Utilities";
	public static final String VERSION = "1.0";
    public static final String DEPENDENCIES = "required-after:Forge@[10.13.0.1180,);";
	
	public static void setMetadata(ModMetadata data)
	{
		data.autogenerated = false;		
		data.url = "http://www.minecraftforum.net/topic/1981778-";
		data.credits = "Kevin for testing and textures";
		data.authorList.add("Dries");
		data.description = "Some cool stuff for advanced farming!";
		data.logoFile = "";
		data.updateUrl = "";
		data.parent = "";
	}
	
	//Paths
	public static final String TEXTURE_LOCATION = ID;

}
